project:
  type: book
  output-dir: _site

book:
  title: "Think Like an AI Engineer"
  subtitle: "Build Systems. Understand Deeply. Apply in Practice."
  author: "Shravan Kumar"
  date: today

  chapters:
    - index.qmd
    - parts/part-1-python-foundations/01_the_ai_engineer_mindset.qmd
    - parts/part-1-python-foundations/02_python_execution_model.qmd
    - parts/part-1-python-foundations/04_numpy_for_ai_engineers.qmd
    - labs/numpy/01_numpy_array_basics.ipynb
    - labs/numpy/02_numpy_vectorized_operations.ipynb
    - labs/numpy/03_numpy_shapes_and_aggregations.ipynb
    - parts/part-1-python-foundations/03_pandas_for_ai_engineers.qmd
    - labs/pandas/01_pandas_basics_practice.ipynb
    - labs/pandas/02_pandas_transformations_practice.ipynb
    - labs/pandas/03_pandas_time_text_practice.ipynb

format:

  html:
    theme: cosmo
    toc: true
    number-sections: true
    number-depth: 2
    code-copy: true

  pdf:
    documentclass: book
    toc: true
    number-sections: true
    number-depth: 2
    fontsize: 11pt
    geometry:
      - margin=1in

execute:
  echo: true
  warning: false
  message: false
